//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.04 at 06:45:21 PM MSK 
//


package ru.geekbrains.backend.buisness.soap.products;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the ru.gbshop.soap.ws.products package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.gbshop.soap.ws.products
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductListRequest }
     */
    public GetProductListRequest createGetProductListRequest() {
        return new GetProductListRequest();
    }

    /**
     * Create an instance of {@link GetProductListResponse }
     */
    public GetProductListResponse createGetProductListResponse() {
        return new GetProductListResponse();
    }

    /**
     * Create an instance of {@link Product }
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link GetProductByTitleRequest }
     */
    public GetProductByTitleRequest createGetProductByTitleRequest() {
        return new GetProductByTitleRequest();
    }

    /**
     * Create an instance of {@link GetProductByTitleResponse }
     */
    public GetProductByTitleResponse createGetProductByTitleResponse() {
        return new GetProductByTitleResponse();
    }

}
